name: Build and Test

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: [main]
  workflow_call:


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup NodeJS (yarn)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install required packages
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test