name: CHANGELOG.md Generation

on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: gem install github_changelog_generator
      - run: github_changelog_generator -u mardisen -p solid-swipe-card
      - name: "Commit changelog"
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated CHANGELOG (Automated)
          add: CHANGELOG.md