name: Generate Coverage Report

on:
  push:
    branches: [main]


jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup NodeJS (yarn)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install required packages
        run: yarn install --immutable
      - name: Coverage
        run: yarn coverage
      - name: Send coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          directory: coverage
          fail_ci_if_error: true
          verbose: true