

name: Node.js Package Publish

on:
  release:
    types: [published]

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup NodeJS (yarn)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: Install required packages
        run: yarn install --immutable --ignore-scripts
      - name: Publish to NPM
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}