name: Node.js Package Publish

on:
  release:
    types: [published]

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
        with:
          auth-token: ${{secrets.NPM_TOKEN}}
          cmd: publish
          
