name: Node.js Package Publish

on:
  release:
    types: [published, edited]

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          cache: npm
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.YARN_TOKEN }}