name: Node.js Package Publish

on:
  release:
    types: [published, edited]

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          cache: npm
      - name: Disable postinstall and prepare script
        run: npm pkg set scripts.postinstall="echo no-postinstall" && npm pkg set scripts.prepare="echo no-prepare"
      - name: Generate package-lock.json
        run: npm install --package-lock-only
      - name: Install Dependencies
        run: npm ci
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}